###
POST http://localhost:9000/api/bands  HTTP/1.1
Content-Type: application/json

{
    "band": "Susana Baca",
    "album": "Lamento Negro",
    "year": "2001",
    "genre": "folclokr afroperuano"
}

###
GET http://localhost:9000/api/bands  HTTP/1.1

###
GET http://localhost:9000/api/bands/639375ebfb1a63024c4b0cd7  HTTP/1.1

###
PUT  http://localhost:9000/api/bands/63943129f8a43ce45b4fe8cb  HTTP/1.1
Content-Type: application/json

{
    "band" : "Jethro Tull",
    "album"  : "Stand Up",
    "year": "1969",
    "genre": "Blues Rock"
}

###
DELETE   http://localhost:9000/api/bands/63943129f8a43ce45b4fe8cb  HTTP/1.1